### ISSUE TITLE
Calendar widget for planning

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/SaddlebackCSS.github.io#4]
Might be nice to have some sort of calendar that we can add to the site to keep track of meeting topics / days club won't be meeting / other calendar type dealies. Could be another page on the site or placed somewhere with high visibility

**Comment by garlic-hub** [comment]
Needs more Jquery. This looks pretty useful: https://fullcalendar.io/. The github for it: https://github.com/fullcalendar/fullcalendar

**Comment by ozyx** [comment]
For the sake of having a functional calendar, I'm going to be embedding a google calendar on a new header page called `Calendar`.

Maybe we can look into fullcalendar as a club project.
